### ISSUE TITLE
Frends.AmazonS3.UploadObject not able to upload files over 5GB and no exception returned

### ISSUE THREAD

**Issue by helvertti** [FrendsPlatform/Frends.AmazonS3#20]
Frends doesn't notice anything wrong with uploading files larger than 5GB: the processes run just fine, the files just simply don't show up in the S3 bucket. We found articles (e.g. https://saturncloud.io/blog/how-to-upload-large-files-to-amazon-s3-as-a-data-scientist/) describing ways of using an AWS SDK for chopping the upload into multiple smaller pieces.
This is possible to implement with Multipart uploading: https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html

Currently library does not support multipart upload, but it might not activated settings for this. It should be investigated how big process is to update current task or whether new task should be created with multipart upload.

**Comment by ttossavainen** [comment]
merged
