### ISSUE TITLE
UploadObject: Add debug log to Task result.

### ISSUE THREAD

**Issue by Svenskapojkarna** [FrendsPlatform/Frends.AmazonS3#8]
A request has been implemented to Frends.Community.AWS.UploadFiles in which the Task will provide debug log of the file transfer as result of the Task: https://github.com/CommunityHiQ/Frends.Community.AWS/issues/22.

This feature helps debugging issues with the file transfer which are not necessarily issues with the Task, but for example AWS S3 configurations or some other things related to S3.

Implementation proposal: https://github.com/CommunityHiQ/Frends.Community.AWS/commit/cbfc6f83acf8d0336f8d5c650976a30648f05257.

**Comment by ttossavainen** [comment]
merged
